id: P000502
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG12539
  title: ཕྱག་ཆེན་ལྔ་ལྡན་སོགས་ཀྱི་ཁྲིད་ཡིག་ཟབ་རྒྱས་རིན་ཆེན་ཕྲེང་བ།
  author: ''
  volumes:
    4acf135eed7b47209ea0f511862315b0:
      image_group_id: I1KG12570
      title: Volume 1 of phyag chen lnga ldan sogs kyi khrid yig zab rgyas rin chen
        phreng ba/
      volume_number: 1
      total_pages: 258
      base_file: v001.txt
